server:
  port: 8000
  servlet:
    context-path: /auth

spring:       
  application:
    name: auth
  profiles:
    active:
      - test
      
  rabbitmq:
    connection-timeout: 5000
    host: localhost
    port: 5672
    username: nando.systempro@hotmail.com
    password: Fe281244
    

logging:
  file:
    name: logs/api.log
  level:
    root: INFO
    com.invest.utils: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      access: ALLOW





