server:
  port: 8000
  servlet:
    context-path: /auth

spring:       
  application:
    name: auth
  profiles:
    active:
      - test
      
  rabbitmq:
    host: localhost
    port: 5672
    username: nando.systempro@hotmail.com
    password: Fe281244
    
    
invest:
  rabbitmq:
    exchange: invest.exchange
    queue: conta.invest.queue
    routingKey: conta.routing.key
