server:
  port: 8001
  servlet:
    context-path: /api/invest

spring:       
  application:
    name: api-invest
  profiles:
    active:
      - test  

  rabbitmq:
    host: localhost
    port: 5672
    username: nando.systempro@hotmail.com
    password: Fe281244
    
    
invest:
  rabbitmq:
    exchange: invest.exchange
    queue: conta.invest.queue
    routingKey: conta.routing.key



  

