server:
  port: 8001
  servlet:
    context-path: /api/rendafixa

spring:       
  application:
    name: api-invest
  profiles:
    active:
      - test  

  rabbitmq:
    connection-timeout: 5000
    host: localhost
    port: 5672
    username: nando.systempro@hotmail.com
    password: Fe281244
    
    


  

