global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Spring Boot / Gateway Proxy
  - job_name: 'gateway-proxy'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # Use host.docker.internal para acessar serviços que rodam no host Windows
      - targets: ['host.docker.internal:8765']

  # RabbitMQ (plugin Prometheus)
  - job_name: 'rabbitmq'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:15692']   # nome do serviço Docker
    basic_auth:
      username: 'nando.systempro@hotmail.com'
      password: 'Fe281244'

  # Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']   # nome do serviço Docker
