server:
  port: 8765

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8000
          predicates:
            - Path=/auth/**

        - id: rendafixa
          uri: http://localhost:8001
          predicates:
            - Path=/rendafixa/**
         

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "Authorization"
              - "Content-Type"
            allowCredentials: true

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    com.syp.gateway: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{requestId}] %-5level %logger{36} - %msg%n"
  file:
    name: logs/gateway.log
