server:
  port: 8765

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8000
          predicates:
            - Path=/auth/**

        - id: rendafixa
          uri: http://localhost:8001
          predicates:
            - Path=/rendafixa/**

      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:4200"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                exposedHeaders:
                  - "Authorization"
                  - "Content-Type"
                allowCredentials: true

management:
  endpoint:
    prometheus:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  file:
    name: logs/api.log
  level:
    root: INFO
    com.invest.utils: DEBUG
