server:
  port: 8765

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8000
          predicates:
            - Path=/auth/**

        - id: rendafixa
          uri: http://localhost:8001
          predicates:
            - Path=/rendafixa/**
         

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "Authorization"
              - "Content-Type"
            allowCredentials: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true
 
