server:
  port: 8765

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: api-invest
              uri: http://localhost:8000
              predicates:
                - Path=/api/invest/**
            - id: api-rendafixa
              uri: http://localhost:8001
              predicates:
                - Path=/api/rendafixa/**
